server:
  # -- Ingress configuration for the Argo CD server
  ingress:
    enabled: true
    # -- We will use the Minikube ingress controller
    ingressClassName: "nginx"
    hosts:
      - argocd.local
    paths:
      - /
    pathType: "Prefix"
