name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-and-format:
    name: Validate and Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0 # Or a version that suits your needs

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Format Check
        id: fmt
        run: terraform fmt -check
        working-directory: ./terraform

      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: ./terraform

  security-scans:
    name: Security Scans
    runs-on: ubuntu-latest
    needs: validate-and-format

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Kubeconfig
        env:
          KUBECONFIG_BASE64: ${{ secrets.KUBECONFIG_BASE64 }}
        run: |
          mkdir -p ~/.kube
          echo "$KUBECONFIG_BASE64" | base64 --decode > ~/.kube/config
          chmod 600 ~/.kube/config
          echo "--- Kubeconfig Content (masked) ---"
          sed -E 's/(client-certificate-data|client-key-data|token): ".*"/\1: "[MASKED]"/g' ~/.kube/config
          echo "--- End Kubeconfig Content ---"
          kubectl config get-contexts
          kubectl config use-context minikube

      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.52.2/trivy_0.52.2_Linux-64bit.deb
          sudo dpkg -i trivy_0.52.2_Linux-64bit.deb

      - name: Run Trivy Vulnerability Scan in Cluster
        run: trivy k8s --kubeconfig ~/.kube/config --report summary cluster

      - name: Run kube-bench
        run: |
          kubectl apply -f security/kube-bench-config.yaml
          kubectl wait --for=condition=complete job/kube-bench
          kubectl logs job/kube-bench > kube-bench-results.txt
          cat kube-bench-results.txt

      - name: Install Kubescape
        run: | 
          curl -s https://raw.githubusercontent.com/kubescape/kubescape/master/install.sh | /bin/bash

      - name: Run Kubescape Scan
        run: |
          kubescape scan --kubeconfig ~/.kube/config --kubecontext minikube --format pretty --output SECURITY-REPORT.md
          cat SECURITY-REPORT.md